# H2 en memoria para desarrollo local
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:productos;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Puerto
quarkus.http.port=8080

# OpenShift deployment config
quarkus.openshift.route.expose=true
quarkus.openshift.resources.requests.cpu=250m
quarkus.openshift.resources.requests.memory=256Mi
quarkus.openshift.resources.limits.cpu=500m
quarkus.openshift.resources.limits.memory=512Mi
